# ===============================
# VERSION & CONSTANTS
# ===============================
APP_VERSION     = "1.1"
GITHUB_USER     = "alysonsb"
GITHUB_REPO     = "RomManagerPro-"
GITHUB_API_URL  = f"https://api.github.com/repos/{GITHUB_USER}/{GITHUB_REPO}/releases/latest"
GITHUB_RELEASES = f"https://github.com/{GITHUB_USER}/{GITHUB_REPO}/releases/latest"

PLATFORM_TOOLS_URLS = {
    "linux":   "https://dl.google.com/android/repository/platform-tools-latest-linux.zip",
    "windows": "https://dl.google.com/android/repository/platform-tools-latest-windows.zip",
    "darwin":  "https://dl.google.com/android/repository/platform-tools-latest-darwin.zip",
}

PAYLOAD_DUMPER_RELEASES_API = "https://api.github.com/repos/ssut/payload-dumper-go/releases/latest"
PAYLOAD_DUMPER_ASSET_PATTERNS = {
    "linux":   "linux_amd64",
    "windows": "windows_amd64",
    "darwin":  "darwin_amd64",
}

MAGISK_API = "https://api.github.com/repos/topjohnwu/Magisk/releases/latest"
KSU_RELEASES_API = "https://api.github.com/repos/tiann/KernelSU/releases/latest"

# ===============================
# TRANSLATIONS
# ===============================
TRANSLATIONS = {
    "pt": {
        "nav_sistema":"🖥  Sistema","nav_apps":"📦  Apps","nav_adb":"⌨  ADB Shell",
        "nav_fastboot":"⚡  Fastboot","nav_aosp":"🗜  Flash AOSP","nav_hyperos":"🔥  Flash HyperOS",
        "donate":"☕  Me doe um cafe","dev_by":"desenvolvido por @alysonsb",
        "tab_sistema":"Sistema","tab_sistema_sub":"Informações do dispositivo",
        "sec_device":"DISPOSITIVO","card_modelo":"Modelo","card_android":"Android",
        "card_serial":"Serial","card_imei":"IMEI","card_ram":"RAM",
        "card_storage":"Armazenamento","card_battery":"Bateria","card_health":"Saúde",
        "btn_refresh":"↻  Atualizar Dados","health_unknown":"Desconhecida","health_good":"Boa ✓",
        "health_overheat":"Superaquecendo","health_dead":"Morta","health_over_volt":"Sobretensão",
        "health_failure":"Falha","health_cold":"Fria","restricted":"Restrito",
        "tab_apps":"Aplicativos","tab_apps_sub":"Pacotes instalados",
        "sec_install_apk":"INSTALAR APK DO PC","apk_placeholder":"Selecione um arquivo .apk...",
        "btn_browse":"📂  Procurar","btn_install":"📲  Instalar no Dispositivo",
        "installing":"⏳  Instalando...","install_ok":"✓  Instalado com sucesso!",
        "sec_packages":"PACOTES DE TERCEIROS","btn_load_apps":"↻  Carregar Apps",
        "packages_found":"{n} pacotes encontrados",
        "sec_debloat":"DEBLOAT — DESATIVAR APPS DO SISTEMA",
        "debloat_hint":"Carrega todos os apps (inclusive do sistema). Selecione múltiplos e clique em Desativar.",
        "debloat_filter":"Filtrar por nome ou pacote...","btn_load_all":"↻  Carregar Todos",
        "btn_disable":"🚫  Desativar Apps","btn_enable":"✅  Reativar Apps",
        "debloat_found":"{n} apps • {s} selecionados","debloat_confirm":"Desativar {n} app(s)?",
        "debloat_confirm_body":"Os apps serão desativados via <b>pm disable-user</b>.",
        "debloat_ok":"✓  Desativar","enable_confirm":"Reativar {n} app(s)?",
        "enable_confirm_body":"Os apps serão reativados via <b>pm enable</b>.","enable_ok":"✓  Reativar",
        "tag_system":"sistema","tag_user":"usuário","tag_disabled":"desativado",
        "menu_open":"🚀  Abrir App","menu_backup":"💾  Backup APK",
        "menu_clear":"🗑  Limpar Dados","menu_uninstall":"❌  Desinstalar",
        "tab_adb":"ADB Shell","tab_adb_sub":"Execute comandos ADB","sec_command":"COMANDO",
        "adb_placeholder":"shell getprop ro.product.model","btn_run":"Executar","btn_clear":"Limpar","sec_output":"SAÍDA",
        "tab_fastboot":"Fastboot","tab_fastboot_sub":"Flash e bootloader","fb_placeholder":"flash boot boot.img",
        "sec_fb_file":"SELECIONAR ARQUIVO PARA FLASH",
        "sec_quick":"AÇÕES RÁPIDAS","btn_devices":"Devices","btn_reboot":"Reboot",
        "btn_bootloader":"Bootloader","btn_recovery_warn":"⚠  Reboot Recovery",
        "tab_aosp":"Flash AOSP","tab_aosp_sub":"Extração de payload.bin e flash de partições",
        "sec_step1":"PASSO 1 — SELECIONAR ROM (.zip)","rom_placeholder":"Selecione o arquivo .zip da ROM...",
        "btn_select_rom":"Selecionar ROM","dumper_label":"Executável  payload-dumper-go",
        "dumper_hint":"Se estiver no PATH, deixe o valor padrão","dumper_placeholder":"payload-dumper-go",
        "btn_select_exe":"Selecionar Executável","sec_step2":"PASSO 2 — EXTRAIR PAYLOAD",
        "partitions_label":"Partições:","btn_extract":"🗜  Iniciar Extração",
        "extract_start_msg":"Selecione uma ROM para começar.",
        "sec_ksu":"PASSO 2.5 — ROOT COM KERNELSU  (opcional)",
        "sec_step3":"PASSO 3 — FLASH DAS PARTIÇÕES",
        "flash_info":"Os comandos abaixo serão gerados automaticamente após a extração.",
        "btn_reboot_fb":"🔄  Reboot Fastboot","btn_flash_now":"⚡  Fazer Flash Agora",
        "btn_reboot_rec":"↩  Reboot Recovery","btn_cleanup":"🗑  Limpar Arquivos","btn_flash_rom":"📲  FLASH ROM",
        "sideload_title":"⚠  Atenção — Antes de continuar","sideload_bold":"<b>Prepare o dispositivo!</b>",
        "sideload_body":"1. Dispositivo no <b>Recovery</b>.<br>2. <b>Apply update → Apply from ADB</b>.<br>",
        "btn_confirm_flash":"✓  Estou pronto, iniciar flash","btn_cancel":"Cancelar",
        "sideload_notice":"⚠  No celular, acesse o recovery → Apply from ADB.\nNão desconecte o cabo.",
        "tab_hyperos":"Flash HyperOS","tab_hyperos_sub":"Extração e flash via scripts oficiais",
        "sec_hyper_step1":"PASSO 1 — SELECIONAR ROM HYPEROS (.zip)",
        "hyper_placeholder":"Selecione o arquivo .zip da ROM HyperOS...",
        "sec_hyper_step2":"PASSO 2 — EXTRAIR E SELECIONAR SCRIPT","btn_hyper_extract":"🗜  Extrair ROM",
        "hyper_start_msg":"Selecione uma ROM HyperOS para começar.",
        "sec_hyper_step3":"PASSO 3 — ESCOLHA O SCRIPT DE FLASH",
        "scripts_hint":"Clique em um script para selecioná-lo. 'update'=OTA, 'clean'=apaga dados.",
        "sec_hyper_step4":"PASSO 4 — EXECUTAR FLASH","no_script":"Nenhum script selecionado.",
        "btn_run_script":"⚡  Executar Script",
        "log_opening_zip":"📦  Abrindo ZIP...",
        "log_payload_not_found":"✗  payload.bin não encontrado!",
        "log_payload_ok":"✓  payload.bin ({size} MB)",
        "log_partitions_found":"\n✓  {n} partição(ões):",
        "log_removed":"\n🗑  Removido.",
        "log_no_rom":"✗  ROM não encontrada.",
        "log_no_fastboot_dev":"✗  Nenhum dispositivo em fastboot!",
        "log_no_rom_selected":"✗  Nenhuma ROM selecionada.",
        "log_sideload_done":"✓  Sideload concluído.",
        "status_disabling":"⏳  Desativando {n}...",
        "status_disabled_ok":"✓  {ok} desativado(s)",
        "status_disabled_err":"  ✗ {err} erro(s)",
        "status_enabling":"⏳  Reativando {n}...",
        "status_enabled_ok":"✓  {ok} reativado(s)",
        "fb_partition_unknown":"⚠  Partição não reconhecida para {fname}. Substitua PARTIÇÃO pelo nome correto.",
        "hyper_files":"📦  {n} arquivos.",
        "hyper_extract_done":"✓  Extração concluída.",
        "hyper_scripts_found":"\n📋  {n} script(s):",
        "hyper_no_script":"✗  Script não encontrado.",
        "btn_reboot_device":"🔄  Reboot",
        "extract_status_ok":"✓  Pronto! {n} arquivo(s).",
        "extract_status_none":"⚠  Nenhuma partição encontrada.",
        "extract_status_err":"✗  Erro ao extrair.",
        "extract_status_no_payload":"✗  payload.bin não encontrado.",
        "log_work_dir":"📁  Diretório de trabalho: {path}",
        "log_extract_err":"✗  Erro: {err}",
    },
    "en": {
        "nav_sistema":"🖥  System","nav_apps":"📦  Apps","nav_adb":"⌨  ADB Shell",
        "nav_fastboot":"⚡  Fastboot","nav_aosp":"🗜  Flash AOSP","nav_hyperos":"🔥  Flash HyperOS",
        "donate":"☕  Buy me a coffee","dev_by":"developed by @alysonsb",
        "tab_sistema":"System","tab_sistema_sub":"Device information",
        "sec_device":"DEVICE","card_modelo":"Model","card_android":"Android","card_serial":"Serial",
        "card_imei":"IMEI","card_ram":"RAM","card_storage":"Storage","card_battery":"Battery","card_health":"Health",
        "btn_refresh":"↻  Refresh Data","health_unknown":"Unknown","health_good":"Good ✓",
        "health_overheat":"Overheating","health_dead":"Dead","health_over_volt":"Over Voltage",
        "health_failure":"Failure","health_cold":"Cold","restricted":"Restricted",
        "tab_apps":"Applications","tab_apps_sub":"Installed packages",
        "sec_install_apk":"INSTALL APK FROM PC","apk_placeholder":"Select an .apk file...",
        "btn_browse":"📂  Browse","btn_install":"📲  Install on Device",
        "installing":"⏳  Installing...","install_ok":"✓  Installed successfully!",
        "sec_packages":"THIRD-PARTY PACKAGES","btn_load_apps":"↻  Load Apps","packages_found":"{n} packages found",
        "sec_debloat":"DEBLOAT — DISABLE SYSTEM APPS",
        "debloat_hint":"Loads all apps including system. Select multiple and click Disable.",
        "debloat_filter":"Filter by name or package...","btn_load_all":"↻  Load All",
        "btn_disable":"🚫  Disable Apps","btn_enable":"✅  Re-enable Apps",
        "debloat_found":"{n} apps • {s} selected","debloat_confirm":"Disable {n} app(s)?",
        "debloat_confirm_body":"Apps will be disabled via <b>pm disable-user</b>.",
        "debloat_ok":"✓  Disable","enable_confirm":"Re-enable {n} app(s)?",
        "enable_confirm_body":"Apps will be re-enabled via <b>pm enable</b>.","enable_ok":"✓  Re-enable",
        "tag_system":"system","tag_user":"user","tag_disabled":"disabled",
        "menu_open":"🚀  Open App","menu_backup":"💾  Backup APK","menu_clear":"🗑  Clear Data","menu_uninstall":"❌  Uninstall",
        "tab_adb":"ADB Shell","tab_adb_sub":"Run ADB commands","sec_command":"COMMAND",
        "adb_placeholder":"shell getprop ro.product.model","btn_run":"Run","btn_clear":"Clear","sec_output":"OUTPUT",
        "tab_fastboot":"Fastboot","tab_fastboot_sub":"Flash & bootloader","fb_placeholder":"flash boot boot.img",
        "sec_fb_file":"SELECT FILE TO FLASH",
        "sec_quick":"QUICK ACTIONS","btn_devices":"Devices","btn_reboot":"Reboot",
        "btn_bootloader":"Bootloader","btn_recovery_warn":"⚠  Reboot Recovery",
        "tab_aosp":"Flash AOSP","tab_aosp_sub":"payload.bin extraction and partition flash",
        "sec_step1":"STEP 1 — SELECT ROM (.zip)","rom_placeholder":"Select the ROM .zip file...",
        "btn_select_rom":"Select ROM","dumper_label":"payload-dumper-go Executable",
        "dumper_hint":"If in PATH, leave default","dumper_placeholder":"payload-dumper-go",
        "btn_select_exe":"Select Executable","sec_step2":"STEP 2 — EXTRACT PAYLOAD",
        "partitions_label":"Partitions:","btn_extract":"🗜  Start Extraction",
        "extract_start_msg":"Select a ROM to begin.","sec_step3":"STEP 3 — FLASH PARTITIONS",
        "flash_info":"Commands will be generated after extraction.",
        "btn_reboot_fb":"🔄  Reboot Fastboot","btn_flash_now":"⚡  Flash Now",
        "btn_reboot_rec":"↩  Reboot Recovery","btn_cleanup":"🗑  Clean Files","btn_flash_rom":"📲  FLASH ROM",
        "sideload_title":"⚠  Warning","sideload_bold":"<b>Prepare your device!</b>",
        "sideload_body":"1. Device in <b>Recovery</b>.<br>2. <b>Apply update → Apply from ADB</b>.<br>",
        "btn_confirm_flash":"✓  Ready, start flash","btn_cancel":"Cancel",
        "sideload_notice":"⚠  On phone, go to recovery → Apply from ADB.\nDo not disconnect cable.",
        "tab_hyperos":"Flash HyperOS","tab_hyperos_sub":"Extraction and flash via official scripts",
        "sec_hyper_step1":"STEP 1 — SELECT HYPEROS ROM (.zip)","hyper_placeholder":"Select HyperOS ROM .zip...",
        "sec_hyper_step2":"STEP 2 — EXTRACT AND SELECT SCRIPT","btn_hyper_extract":"🗜  Extract ROM",
        "hyper_start_msg":"Select a HyperOS ROM to begin.","sec_hyper_step3":"STEP 3 — CHOOSE FLASH SCRIPT",
        "scripts_hint":"Click a script to select it. 'update'=OTA, 'clean'=wipe data.",
        "sec_hyper_step4":"STEP 4 — RUN FLASH","no_script":"No script selected.","btn_run_script":"⚡  Run Script",
        "log_opening_zip":"📦  Opening ZIP...",
        "log_payload_not_found":"✗  payload.bin not found!",
        "log_payload_ok":"✓  payload.bin ({size} MB)",
        "log_partitions_found":"\n✓  {n} partition(s):",
        "log_removed":"\n🗑  Removed.",
        "log_no_rom":"✗  ROM not found.",
        "log_no_fastboot_dev":"✗  No device in fastboot!",
        "log_no_rom_selected":"✗  No ROM selected.",
        "log_sideload_done":"✓  Sideload complete.",
        "status_disabling":"⏳  Disabling {n}...",
        "status_disabled_ok":"✓  {ok} disabled",
        "status_disabled_err":"  ✗ {err} error(s)",
        "status_enabling":"⏳  Re-enabling {n}...",
        "status_enabled_ok":"✓  {ok} re-enabled",
        "fb_partition_unknown":"⚠  Unknown partition for {fname}. Replace PARTITION with correct name.",
        "hyper_files":"📦  {n} files.",
        "hyper_extract_done":"✓  Extraction complete.",
        "hyper_scripts_found":"\n📋  {n} script(s):",
        "hyper_no_script":"✗  Script not found.",
        "btn_reboot_device":"🔄  Reboot",
        "extract_status_ok":"✓  Done! {n} file(s).",
        "extract_status_none":"⚠  No partitions found.",
        "extract_status_err":"✗  Extraction error.",
        "extract_status_no_payload":"✗  payload.bin not found.",
        "log_work_dir":"📁  Work directory: {path}",
        "log_extract_err":"✗  Error: {err}",
    },
    "es": {
        "nav_sistema":"🖥  Sistema","nav_apps":"📦  Apps","nav_adb":"⌨  ADB Shell",
        "nav_fastboot":"⚡  Fastboot","nav_aosp":"🗜  Flash AOSP","nav_hyperos":"🔥  Flash HyperOS",
        "donate":"☕  Invítame un café","dev_by":"desarrollado por @alysonsb",
        "tab_sistema":"Sistema","tab_sistema_sub":"Información del dispositivo",
        "sec_device":"DISPOSITIVO","card_modelo":"Modelo","card_android":"Android","card_serial":"Serial",
        "card_imei":"IMEI","card_ram":"RAM","card_storage":"Almacenamiento","card_battery":"Batería","card_health":"Salud",
        "btn_refresh":"↻  Actualizar","health_unknown":"Desconocida","health_good":"Buena ✓",
        "health_overheat":"Sobrecalentando","health_dead":"Muerta","health_over_volt":"Sobretensión",
        "health_failure":"Falla","health_cold":"Fría","restricted":"Restringido",
        "tab_apps":"Aplicaciones","tab_apps_sub":"Paquetes instalados",
        "sec_install_apk":"INSTALAR APK","apk_placeholder":"Seleccione un .apk...",
        "btn_browse":"📂  Explorar","btn_install":"📲  Instalar","installing":"⏳  Instalando...",
        "install_ok":"✓  ¡Instalado!","sec_packages":"PAQUETES DE TERCEROS","btn_load_apps":"↻  Cargar Apps",
        "packages_found":"{n} paquetes","sec_debloat":"DEBLOAT — DESHABILITAR APPS",
        "debloat_hint":"Carga todos los apps incluyendo sistema.","debloat_filter":"Filtrar...",
        "btn_load_all":"↻  Cargar Todos","btn_disable":"🚫  Deshabilitar","btn_enable":"✅  Reactivar",
        "debloat_found":"{n} apps • {s} seleccionados","debloat_confirm":"¿Deshabilitar {n} app(s)?",
        "debloat_confirm_body":"Las apps se deshabilitarán con <b>pm disable-user</b>.",
        "debloat_ok":"✓  Deshabilitar","enable_confirm":"¿Reactivar {n} app(s)?",
        "enable_confirm_body":"Las apps se reactivarán con <b>pm enable</b>.","enable_ok":"✓  Reactivar",
        "tag_system":"sistema","tag_user":"usuario","tag_disabled":"deshabilitado",
        "menu_open":"🚀  Abrir","menu_backup":"💾  Backup APK","menu_clear":"🗑  Limpiar","menu_uninstall":"❌  Desinstalar",
        "tab_adb":"ADB Shell","tab_adb_sub":"Ejecutar comandos ADB","sec_command":"COMANDO",
        "adb_placeholder":"shell getprop ro.product.model","btn_run":"Ejecutar","btn_clear":"Limpiar","sec_output":"SALIDA",
        "tab_fastboot":"Fastboot","tab_fastboot_sub":"Flash y bootloader","fb_placeholder":"flash boot boot.img",
        "sec_fb_file":"SELECCIONAR ARCHIVO PARA FLASH",
        "sec_quick":"ACCIONES RÁPIDAS","btn_devices":"Devices","btn_reboot":"Reboot",
        "btn_bootloader":"Bootloader","btn_recovery_warn":"⚠  Reboot Recovery",
        "tab_aosp":"Flash AOSP","tab_aosp_sub":"Extracción payload.bin y flash",
        "sec_step1":"PASO 1 — SELECCIONAR ROM","rom_placeholder":"Seleccione el .zip de la ROM...",
        "btn_select_rom":"Seleccionar ROM","dumper_label":"Ejecutable payload-dumper-go",
        "dumper_hint":"Si está en PATH, deje el valor predeterminado","dumper_placeholder":"payload-dumper-go",
        "btn_select_exe":"Seleccionar Ejecutable","sec_step2":"PASO 2 — EXTRAER PAYLOAD",
        "partitions_label":"Particiones:","btn_extract":"🗜  Iniciar Extracción",
        "extract_start_msg":"Seleccione una ROM.","sec_step3":"PASO 3 — FLASH",
        "flash_info":"Los comandos se generarán automáticamente.",
        "btn_reboot_fb":"🔄  Reboot Fastboot","btn_flash_now":"⚡  Flash Ahora",
        "btn_reboot_rec":"↩  Reboot Recovery","btn_cleanup":"🗑  Limpiar","btn_flash_rom":"📲  FLASH ROM",
        "sideload_title":"⚠  Atención","sideload_bold":"<b>¡Prepare el dispositivo!</b>",
        "sideload_body":"1. <b>Recovery</b>.<br>2. <b>Apply from ADB</b>.<br>",
        "btn_confirm_flash":"✓  Listo","btn_cancel":"Cancelar",
        "sideload_notice":"⚠  Seleccione Apply from ADB en recovery.",
        "tab_hyperos":"Flash HyperOS","tab_hyperos_sub":"Flash mediante scripts oficiales",
        "sec_hyper_step1":"PASO 1 — SELECCIONAR ROM HYPEROS","hyper_placeholder":"Seleccione el .zip HyperOS...",
        "sec_hyper_step2":"PASO 2 — EXTRAER Y SELECCIONAR SCRIPT","btn_hyper_extract":"🗜  Extraer ROM",
        "hyper_start_msg":"Seleccione una ROM HyperOS.","sec_hyper_step3":"PASO 3 — ELEGIR SCRIPT",
        "scripts_hint":"Haga clic en un script.","sec_hyper_step4":"PASO 4 — EJECUTAR",
        "no_script":"Ningún script seleccionado.","btn_run_script":"⚡  Ejecutar Script",
        "log_opening_zip":"📦  Abriendo ZIP...",
        "log_payload_not_found":"✗  ¡payload.bin no encontrado!",
        "log_payload_ok":"✓  payload.bin ({size} MB)",
        "log_partitions_found":"\n✓  {n} partición(es):",
        "log_removed":"\n🗑  Eliminado.",
        "log_no_rom":"✗  ROM no encontrada.",
        "log_no_fastboot_dev":"✗  ¡Ningún dispositivo en fastboot!",
        "log_no_rom_selected":"✗  Ninguna ROM seleccionada.",
        "log_sideload_done":"✓  Sideload completo.",
        "status_disabling":"⏳  Deshabilitando {n}...",
        "status_disabled_ok":"✓  {ok} deshabilitado(s)",
        "status_disabled_err":"  ✗ {err} error(es)",
        "status_enabling":"⏳  Reactivando {n}...",
        "status_enabled_ok":"✓  {ok} reactivado(s)",
        "fb_partition_unknown":"⚠  Partición desconocida para {fname}. Reemplace PARTICIÓN con el nombre correcto.",
        "hyper_files":"📦  {n} archivos.",
        "hyper_extract_done":"✓  Extracción completa.",
        "hyper_scripts_found":"\n📋  {n} script(s):",
        "hyper_no_script":"✗  Script no encontrado.",
        "btn_reboot_device":"🔄  Reboot",
        "extract_status_ok":"✓  ¡Listo! {n} archivo(s).",
        "extract_status_none":"⚠  No se encontraron particiones.",
        "extract_status_err":"✗  Error de extracción.",
        "extract_status_no_payload":"✗  payload.bin no encontrado.",
        "log_work_dir":"📁  Directorio de trabajo: {path}",
        "log_extract_err":"✗  Error: {err}",
    },
    "ru": {
        "nav_sistema":"🖥  Система","nav_apps":"📦  Приложения","nav_adb":"⌨  ADB Shell",
        "nav_fastboot":"⚡  Fastboot","nav_aosp":"🗜  Flash AOSP","nav_hyperos":"🔥  Flash HyperOS",
        "donate":"☕  Угостить кофе","dev_by":"разработано @alysonsb",
        "tab_sistema":"Система","tab_sistema_sub":"Информация об устройстве",
        "sec_device":"УСТРОЙСТВО","card_modelo":"Модель","card_android":"Android","card_serial":"Серийный номер",
        "card_imei":"IMEI","card_ram":"ОЗУ","card_storage":"Хранилище","card_battery":"Батарея","card_health":"Состояние",
        "btn_refresh":"↻  Обновить","health_unknown":"Неизвестно","health_good":"Хорошее ✓",
        "health_overheat":"Перегрев","health_dead":"Мёртвая","health_over_volt":"Перенапряжение",
        "health_failure":"Сбой","health_cold":"Холодная","restricted":"Ограничено",
        "tab_apps":"Приложения","tab_apps_sub":"Установленные пакеты",
        "sec_install_apk":"УСТАНОВИТЬ APK","apk_placeholder":"Выберите файл .apk...",
        "btn_browse":"📂  Обзор","btn_install":"📲  Установить","installing":"⏳  Установка...",
        "install_ok":"✓  Установлено!","sec_packages":"СТОРОННИЕ ПАКЕТЫ","btn_load_apps":"↻  Загрузить",
        "packages_found":"{n} пакетов","sec_debloat":"ДЕБLOАТ — ОТКЛЮЧИТЬ ПРИЛОЖЕНИЯ",
        "debloat_hint":"Загружает все приложения включая системные.","debloat_filter":"Фильтр...",
        "btn_load_all":"↻  Загрузить все","btn_disable":"🚫  Отключить","btn_enable":"✅  Включить",
        "debloat_found":"{n} приложений • {s} выбрано","debloat_confirm":"Отключить {n}?",
        "debloat_confirm_body":"Через <b>pm disable-user</b>.","debloat_ok":"✓  Отключить",
        "enable_confirm":"Включить {n}?","enable_confirm_body":"Через <b>pm enable</b>.","enable_ok":"✓  Включить",
        "tag_system":"система","tag_user":"пользователь","tag_disabled":"отключено",
        "menu_open":"🚀  Открыть","menu_backup":"💾  Резервная копия","menu_clear":"🗑  Очистить","menu_uninstall":"❌  Удалить",
        "tab_adb":"ADB Shell","tab_adb_sub":"Выполнить команды ADB","sec_command":"КОМАНДА",
        "adb_placeholder":"shell getprop ro.product.model","btn_run":"Выполнить","btn_clear":"Очистить","sec_output":"ВЫВОД",
        "tab_fastboot":"Fastboot","tab_fastboot_sub":"Прошивка и загрузчик","fb_placeholder":"flash boot boot.img",
        "sec_fb_file":"ВЫБРАТЬ ФАЙЛ ДЛЯ ПРОШИВКИ",
        "sec_quick":"БЫСТРЫЕ ДЕЙСТВИЯ","btn_devices":"Устройства","btn_reboot":"Перезагрузка",
        "btn_bootloader":"Загрузчик","btn_recovery_warn":"⚠  Reboot Recovery",
        "tab_aosp":"Flash AOSP","tab_aosp_sub":"Извлечение payload.bin и прошивка",
        "sec_step1":"ШАГ 1 — ВЫБРАТЬ ROM","rom_placeholder":"Выберите .zip с ROM...",
        "btn_select_rom":"Выбрать ROM","dumper_label":"Исполняемый payload-dumper-go",
        "dumper_hint":"Если в PATH, оставьте по умолчанию","dumper_placeholder":"payload-dumper-go",
        "btn_select_exe":"Выбрать исполняемый","sec_step2":"ШАГ 2 — ИЗВЛЕЧЬ PAYLOAD",
        "partitions_label":"Разделы:","btn_extract":"🗜  Начать извлечение",
        "extract_start_msg":"Выберите ROM для начала.","sec_step3":"ШАГ 3 — ПРОШИВКА",
        "flash_info":"Команды будут созданы автоматически.",
        "btn_reboot_fb":"🔄  Reboot Fastboot","btn_flash_now":"⚡  Прошить",
        "btn_reboot_rec":"↩  Reboot Recovery","btn_cleanup":"🗑  Удалить","btn_flash_rom":"📲  FLASH ROM",
        "sideload_title":"⚠  Внимание","sideload_bold":"<b>Подготовьте устройство!</b>",
        "sideload_body":"1. <b>Recovery</b>.<br>2. <b>Apply from ADB</b>.<br>",
        "btn_confirm_flash":"✓  Готов","btn_cancel":"Отмена",
        "sideload_notice":"⚠  Выберите Apply from ADB в recovery.",
        "tab_hyperos":"Flash HyperOS","tab_hyperos_sub":"Прошивка через официальные скрипты",
        "sec_hyper_step1":"ШАГ 1 — ВЫБРАТЬ ROM HYPEROS","hyper_placeholder":"Выберите .zip ROM HyperOS...",
        "sec_hyper_step2":"ШАГ 2 — ИЗВЛЕЧЬ И ВЫБРАТЬ СКРИПТ","btn_hyper_extract":"🗜  Извлечь ROM",
        "hyper_start_msg":"Выберите ROM HyperOS.","sec_hyper_step3":"ШАГ 3 — ВЫБРАТЬ СКРИПТ ПРОШИВКИ",
        "scripts_hint":"Нажмите на скрипт для выбора.","sec_hyper_step4":"ШАГ 4 — ВЫПОЛНИТЬ",
        "no_script":"Скрипт не выбран.","btn_run_script":"⚡  Запустить скрипт",
    },
}

def tr(lang, key, **kwargs):
    text = TRANSLATIONS.get(lang, TRANSLATIONS["pt"]).get(key, key)
    return text.format(**kwargs) if kwargs else text